- name: install nginx and start nginx
  hosts: target
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes