- name: Play level variables
  hosts: local
  connection: local
  vars_file:
    vars.yaml

  tasks:
  - name: varaible printing learning
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "My self {{STUDENT}} learning {{COURSE}} for {{DURATION}}"